# Generated by Django 3.1.6 on 2021-08-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_inspection_id', models.IntegerField(default=-1)),
                ('defect_type', models.CharField(default='null', max_length=255)),
                ('number_of_defects', models.IntegerField(default=0)),
                ('defect_ratio', models.FloatField(default=0)),
                ('defect_grade', models.CharField(default='null', max_length=255)),
                ('defected_image', models.CharField(default='null', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInspectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='null', max_length=255)),
                ('generate_report', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('report_id', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='inspection.reportmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_inspection_id', models.IntegerField(default=-1)),
                ('type', models.CharField(default='null', max_length=255)),
                ('generate_report', models.BooleanField(default=False)),
                ('initial_frame', models.CharField(default='null', max_length=255)),
                ('frame', models.CharField(default='null', max_length=255)),
                ('grey_frame', models.CharField(default='null', max_length=255)),
                ('difference', models.CharField(default='null', max_length=255)),
                ('img_edges_b_rotation', models.CharField(default='null', max_length=255)),
                ('dilation_b_rotation', models.CharField(default='null', max_length=255)),
                ('rotated_image', models.CharField(default='null', max_length=255)),
                ('img_edges_a_rotation', models.CharField(default='null', max_length=255)),
                ('cropped_image', models.CharField(default='null', max_length=255)),
                ('grey_cropped_image', models.CharField(default='null', max_length=255)),
                ('blurred_cropped_image', models.CharField(default='null', max_length=255)),
                ('enhanced_image', models.CharField(default='null', max_length=255)),
                ('standard_image', models.CharField(default='null', max_length=255)),
                ('image_to_compare', models.CharField(default='null', max_length=255)),
                ('binary_cropped', models.CharField(default='null', max_length=255)),
                ('morphed_cropped', models.CharField(default='null', max_length=255)),
                ('defected_image', models.CharField(default='null', max_length=255)),
                ('cracks', models.IntegerField(default=0)),
                ('spot', models.IntegerField(default=0)),
                ('pinhole', models.IntegerField(default=0)),
                ('number_of_defects', models.IntegerField(default=0)),
                ('defect_ratio', models.CharField(default='null', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.employeemodel')),
            ],
        ),
    ]
