# Generated by Django 3.1.6 on 2021-03-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
