# Generated by Django 3.1.6 on 2021-08-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinspectionmodel',
            name='report_id',
        ),
    ]
