# Generated by Django 3.1.6 on 2021-03-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_auto_20210326_0447'),
    ]

    operations = [
        migrations.CreateModel(
            name='inspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grey', models.ImageField(blank=True, upload_to='media/grey')),
                ('diff', models.ImageField(blank=True, upload_to='media/difference')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.employee')),
            ],
        ),
    ]
