# Generated by Django 3.1.6 on 2021-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0004_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspect',
            name='diff',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='inspect',
            name='grey',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
