# Generated by Django 3.1.6 on 2021-03-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_auto_20210329_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='null', max_length=255)),
                ('generate_report', models.BooleanField(default=False)),
                ('first_frame', models.CharField(default='null', max_length=255)),
                ('grey_frame', models.CharField(default='null', max_length=255)),
                ('difference', models.CharField(default='null', max_length=255)),
                ('edge', models.CharField(default='null', max_length=255)),
                ('rotated_image', models.CharField(default='null', max_length=255)),
                ('dilated_image', models.CharField(default='null', max_length=255)),
                ('cropped_image', models.CharField(default='null', max_length=255)),
                ('enhanced_image', models.CharField(default='null', max_length=255)),
                ('binary_image', models.CharField(default='null', max_length=255)),
                ('defected_image', models.CharField(default='null', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspection.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='inspect',
        ),
    ]
