# Generated by Django 3.1.6 on 2021-04-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0006_auto_20210330_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='EmployeeModel',
        ),
        migrations.RenameModel(
            old_name='Inspection',
            new_name='InspectionModel',
        ),
    ]
