# Generated by Django 3.1.6 on 2021-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0007_auto_20210402_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionmodel',
            old_name='binary_image',
            new_name='binary_cropped',
        ),
        migrations.RenameField(
            model_name='inspectionmodel',
            old_name='dilated_image',
            new_name='blurred_cropped_image',
        ),
        migrations.RenameField(
            model_name='inspectionmodel',
            old_name='edge',
            new_name='dilation_b_rotation',
        ),
        migrations.RenameField(
            model_name='inspectionmodel',
            old_name='first_frame',
            new_name='frame',
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='grey_cropped_image',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='image_to_compare',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='img_edges_a_rotation',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='img_edges_b_rotation',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='initial_frame',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='morphed_cropped',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='standard_image',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
