# Generated by Django 3.1.6 on 2021-08-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0008_auto_20210406_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('defect_type', models.CharField(default='null', max_length=255)),
                ('number_of_defects', models.IntegerField(default=0)),
                ('defect_ratio', models.FloatField(default=0)),
                ('defect_grade', models.CharField(default='null', max_length=255)),
                ('defected_image', models.CharField(default='null', max_length=255)),
            ],
        ),
    ]
