# Generated by Django 3.1.6 on 2021-08-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0009_reportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmodel',
            name='cracks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='number_of_defects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='pinhole',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inspectionmodel',
            name='spots',
            field=models.IntegerField(default=0),
        ),
    ]
