# Generated by Django 3.1.6 on 2021-08-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0011_auto_20210819_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinspectionmodel',
            name='inspection_id',
        ),
    ]
