# Generated by Django 3.1.6 on 2021-08-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0013_userinspectionmodel_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionmodel',
            old_name='spots',
            new_name='spot',
        ),
    ]
