# Generated by Django 3.1.6 on 2021-08-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0015_userinspectionmodel_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmodel',
            name='defect_ratio',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
